#database configuration

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam
    username: root
    password: Rakeshkumar@2002


#jpa configuration
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true

