#database configuration

spring:



#jpa configuration
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true

  profiles:
    active: ${ENV:dev}